version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - similar-items-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fec

  similar-items:
    image: node:12-alpine
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - 8001:8001
    working_dir: /similar-items
    volumes:
      - ./:/similar-items
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: fec

volumes:
  similar-items-mysql-data: